import os
import sys
from dataclasses import dataclass

import pandas as pd
from sklearn.model_selection import train_test_split

from src.exception import CustomException
from src.logger import logging


@dataclass
class DataIngestionConfig:
    train_data_path: str = os.path.join("artifacts", "train.csv")
    test_data_path: str  = os.path.join("artifacts", "test.csv")
    raw_data_path: str   = os.path.join("artifacts", "data.csv")


class DataIngestion:
    def __init__(self):
        self.data_ingestion_config = DataIngestionConfig()

    def initiate_data_ingestion(self):
        logging.info("Data Ingestion started")

        try:
            # Read the labeled dataset (generated by label_generator.py)
            # This file contains the Career_Track column which is the real
            # prediction target. Run label_generator.py once before training
            # to create this file.
            df = pd.read_csv(os.path.join("data", "student_profiles_labeled.csv"))

            logging.info(f"Dataset read: {df.shape[0]} rows, {df.shape[1]} columns")
            logging.info(f"Target distribution:\n{df['Career_Track'].value_counts().to_string()}")

            os.makedirs(
                os.path.dirname(self.data_ingestion_config.train_data_path),
                exist_ok=True
            )

            df.to_csv(self.data_ingestion_config.raw_data_path, index=False)

            # Stratified split — ensures each career track is proportionally
            # represented in both train and test sets
            train_set, test_set = train_test_split(
                df,
                test_size=0.2,
                random_state=42,
                stratify=df["Career_Track"]
            )

            train_set.to_csv(self.data_ingestion_config.train_data_path, index=False, header=True)
            test_set.to_csv(self.data_ingestion_config.test_data_path,  index=False, header=True)

            logging.info(
                f"Train/test split done — train: {len(train_set)}, test: {len(test_set)}"
            )

            return (
                self.data_ingestion_config.train_data_path,
                self.data_ingestion_config.test_data_path,
            )

        except Exception as e:
            raise CustomException(e, sys)